name: kanban_board
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  dropdown_button2: ^1.9.0
  # localization
  intl: ^0.17.0
  # assets
  flutter_svg: ^1.1.6
  # debugging
  logger: ^1.1.0
  dio_http_formatter: ^2.1.0
  # state management
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  # ui helpers
  flutter_spinkit: ^5.1.0
  toast: ^0.3.0
  # networking
  dio: ^4.0.6
  # data storage
  shared_preferences: ^2.0.15

  # local DB
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  get_it: ^7.2.0
  # design
  flutter_screenutil: ^5.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
#  assets:
#    - assets/images/
#    - assets/images/2x/
#    - assets/images/3x/
#    - assets/fonts/
#    - assets/lang/
#  fonts:
#    - family: AlmaraiBold
#      fonts:
#        - asset: assets/fonts/almarai_bold.ttf
#
#    - family: AlmaraiRegular
#      fonts:
#        - asset: assets/fonts/almarai_regular.ttf
#
#    - family: Header
#      fonts:
#        - asset: assets/fonts/header_font.ttf
